Repository kaleidawave/ezno, pull requests merged in 2024-11, with the labels that each got.

#213 feat: support `Object.seal` object `Object.preventExtensions`
  checker/definitions/internal.ts.d.bin
  checker/definitions/overrides.d.ts
  checker/definitions/simple.d.ts
  checker/specification/specification.md
  checker/src/context/information.rs
  checker/src/context/mod.rs
  checker/src/features/constant_functions.rs
  checker/src/types/properties/assignment.rs
  checker/src/types/subtyping.rs
Labels: bug, checking, ready

#202 Add watch mode support
  Cargo.lock
  Cargo.toml
  checker/src/options.rs
  src/cli.rs
  src/lib.rs
  src/utilities.rs
Labels: enhancement, cli, ready

#216 fix: synthesize shape in sub-environment scope
  checker/specification/specification.md
  checker/src/synthesis/functions.rs
Labels: bug, checking

#218 feat: enhance template literal type printing
  checker/specification/specification.md
  checker/src/types/printing.rs
Labels: enhancement, checking, diagnostics

#214 Improve CI setup + other fixes
  .github/workflows/clippy-rustfmt-fix.yml
  .github/workflows/github-release.yml
  .github/workflows/performance-and-size.yml
  .github/workflows/publish.yml
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  README.md
  checker/Cargo.toml
  checker/examples/run_checker.rs
  checker/fuzz/fuzz_targets/check_project_naive.rs
  checker/specification/build.rs
  checker/specification/specification.md
  checker/specification/test.rs
  checker/src/context/invocation.rs
  checker/src/diagnostics.rs
  checker/src/features/regexp.rs
  checker/src/lib.rs
  checker/src/synthesis/interactive.rs
  checker/src/synthesis/interfaces.rs
  checker/src/synthesis/mod.rs
  checker/tests/partial_source.rs
  checker/tests/suggestions.rs
  checker/tests/type_mappings.rs
  parser/examples/duplicate_block.rs
  parser/examples/parse.rs
  parser/examples/simple.rs
  parser/src/block.rs
  parser/src/declarations/mod.rs
  parser/src/extensions/jsx.rs
  parser/src/functions/mod.rs
  parser/src/lexer.rs
  parser/src/lib.rs
  parser/src/modules.rs
  parser/src/tokens.rs
  parser/src/types/type_annotations.rs
  src/ast_explorer.rs
  src/build.rs
  src/check.rs
  src/cli.rs
  src/js-based-plugin/index.mjs
  src/js-cli-and-library/package-lock.json
  src/js-cli-and-library/package.json
  src/js-cli-and-library/src/cli.js
  src/js-cli-and-library/test.mjs
  src/js-cli-and-library/tests/cli.test.mjs
  src/js-cli-and-library/tests/library.test.mjs
  src/lib.rs
  src/main.rs
  src/repl.rs
  src/reporting.rs
  src/utilities.rs
  src/wasm_bindings.rs
Labels: internal-improvements, compiler-performance, js-wasm-unplugin-and-playground, cli
